import { and, eq, sql } from "drizzle-orm";
import type { NextRequest } from "next/server";
import { requireTask } from "@/lib/auth/resources";
import { getDb } from "@/lib/db/client";
import { memberships, milestones, tasks } from "@/lib/db/schema";
import { recordActivity } from "@/lib/activity";
import { apiError, assertSameOrigin, ok, parseJson } from "@/lib/http/api";
import { ApiError } from "@/lib/http/errors";
import { taskUpdateSchema } from "@/lib/validation";
import { createNotification } from "@/lib/notifications";

type Context = { params: Promise<{ taskId: string }> };
export async function GET(request: NextRequest, context: Context) { try { const { taskId } = await context.params; return ok((await requireTask(request, taskId)).task); } catch (error) { return apiError(error); } }
export async function PATCH(request: NextRequest, context: Context) { try { assertSameOrigin(request); const { taskId } = await context.params; const access = await requireTask(request, taskId); const input = await parseJson(request, taskUpdateSchema); const { version, dueDate, ...patch } = input; if (patch.assigneeId) { const [member] = await getDb().select({ id: memberships.id }).from(memberships).where(and(eq(memberships.workspaceId, access.project.workspaceId), eq(memberships.userId, patch.assigneeId))).limit(1); if (!member) throw new ApiError(422, "invalid_assignee", "Die ausgewählte Person gehört nicht zum Workspace."); } if (patch.milestoneId) { const [milestone] = await getDb().select({ id: milestones.id }).from(milestones).where(and(eq(milestones.id, patch.milestoneId), eq(milestones.projectId, access.project.id))).limit(1); if (!milestone) throw new ApiError(422, "invalid_milestone", "Der Meilenstein gehört nicht zum Projekt."); } const [task] = await getDb().update(tasks).set({ ...patch, dueDate: dueDate === undefined ? access.task.dueDate : dueDate ? new Date(`${dueDate}T12:00:00Z`) : null, completedAt: patch.status === "done" ? new Date() : patch.status ? null : access.task.completedAt, version: sql`${tasks.version} + 1`, updatedAt: new Date() }).where(and(eq(tasks.id, taskId), eq(tasks.version, version))).returning(); if (!task) throw new ApiError(409, "version_conflict", "Die Aufgabe wurde inzwischen geändert. Bitte neu laden.", { currentVersion: access.task.version }); await recordActivity({ workspaceId: access.project.workspaceId, actorId: access.user.id, entityType: "task", entityId: taskId, action: "task.updated", payload: input, undoPayload: access.task }); if (patch.assigneeId && patch.assigneeId !== access.task.assigneeId && patch.assigneeId !== access.user.id) await createNotification({ workspaceId: access.project.workspaceId, userId: patch.assigneeId, actorId: access.user.id, type: "task.assigned", title: "Aufgabe zugewiesen", body: task.title, entityType: "task", entityId: task.id }); return ok(task); } catch (error) { return apiError(error); } }
export async function DELETE(request: NextRequest, context: Context) { try { assertSameOrigin(request); const { taskId } = await context.params; const access = await requireTask(request, taskId); const [task] = await getDb().update(tasks).set({ deletedAt: new Date(), version: sql`${tasks.version} + 1`, updatedAt: new Date() }).where(eq(tasks.id, taskId)).returning(); await recordActivity({ workspaceId: access.project.workspaceId, actorId: access.user.id, entityType: "task", entityId: taskId, action: "task.deleted", undoPayload: access.task }); return ok(task); } catch (error) { return apiError(error); } }
